<? /** @var View $this */

use Base\View; ?>


<h2>Вход</h2>

<? if ($this->message) { ?>
	<h4 style="color:red;"><?= $this->message ?></h4>
<? } ?>

<form action="/user/login" METHOD="POST">
	<input type="text" name="login" placeholder="Логин (Email)" value="<?= $this->login ?>" required>
	<input type="text" name="password" placeholder="Пароль" required>
	<input type="submit" value="Войти">
</form>

<a href="/user/register">Хочу зарегистрироваться</a>
