<? /** @var View $this */

use Base\View; ?>

<h2>Регистрация</h2>

<? if ($this->message) { ?>
	<h4 style="color:red;"><?= $this->message ?></h4>
<? } ?>

<form action="/user/register" METHOD="POST">
	<input type="text" name="fio" placeholder="ФИО" value="<?= $this->fio ?>" required>
	<input type="text" name="login" placeholder="Логин" value="<?= $this->login ?>" required>
	<input type="text" name="password" placeholder="Пароль" required>
	<input type="text" name="password_confirmation" placeholder="Повторите пароль" required>
	<input type="submit" value="Регистрация">
</form>

<a href="/user/login">Уже зарегистрирован</a>
