<h1>Блог</h1>
<h4>Привет, <?= $this->user->getFio() ?>! <a style="font-size:12px;" href="/user/logout">[Выход]</a></h4>

<? if ($this->notice): ?>
	<div style="padding:20px; background-color: #fff8cb; font-size: 20px;"><?= $this->notice ?></div>
<? endif; ?>

<form enctype="multipart/form-data" method="POST" action="/message/new">
	<h4>Напишите сообщение:</h4>
	<div style="max-width:400px;margin-bottom:50px;">

		<textarea name="text" rows="3" required></textarea>

		<div style="display: flex; justify-content: space-between;margin-top:10px;">
			<div>
				<input type="file" name="file">
			</div>
			<div>
				<button type="submit">Отправить</button>
			</div>
		</div>
	</div>
</form>

<div class="messages">
    <? if ($this->messages): ?>
        <? foreach ($this->messages as $message):
            $user = $this->authors[$message['user_id']] ?? null;
            ?>
			 <div class="message__w">
              <? if ($this->user->isAdmin()):?>
					  <div class="message__delete-w">
						  <a href="/message/delete?id=<?= $message['id'] ?>"
							  onclick="if(!confirm('Удалить сообщение?')){return false;}"
							  class="message__delete-btn">удалить</a>
					  </div>
              <? endif; ?>
				 <div class="message__date"><?= $message['created_at'] ?></div>
				 <div class="message__text">
					 <b><?= $user ? $user['fio'] : 'Неизвестный' ?></b>: <?= $message['text'] ?>
				 </div>
              <? if ($message['fileurl']):?>
					  <img src="<?= $message['fileurl'] ?>" class="message__img">
              <? endif; ?>
			 </div>
        <? endforeach; ?>
    <? endif; ?>
</div>


<style>
	input, textarea {
		width: 100%;
	}

	.message__w {
		margin-bottom: 15px;
		padding: 5px;
		border: solid 1px #666;
		border-radius: 10px;
		position: relative
	}

	.message__delete-w {
		position: absolute;
		top: 10px;
		right: 10px;
		z-index: 1
	}

	.message__delete-btn {
		color: red;
		font-size: 10px;
	}

	.message__date {
		font-size: 10px;
		font-style: italic;
	}

	.message__text {
		font-size: 12px;
		padding-top: 10px;
	}

	.message__img {
		padding-top: 10px;
		max-width: 200px;
		max-height: 100px;
	}
</style>
