<?php

namespace App\Models;

class Message extends AbstractModel
{
    protected string $table = 'messages';
    protected array $fields = [
        'id' => null,
        'user_id' => null,
        'text' => null,
        'fileurl' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    public function getUserId(): string
    {
        return $this->fields['user_id'];
    }

    public function setUserId(string $fio): self
    {
        $this->fields['user_id'] = trim($fio);
        return $this->setUpdatedAt();
    }

    public function getText(): string
    {
        return $this->fields['text'];
    }

    public function setText(string $text): self
    {
        $this->fields['text'] = trim($text);
        return $this->setUpdatedAt();
    }

    public function setFileurl(string $text): self
    {
        $this->fields['fileurl'] = trim($text);
        return $this->setUpdatedAt();
    }

    public function delete()
    {
        if (!empty($this->getFileurl()) && file_exists(DOC_ROOT . $this->getFileurl())) {
            unlink(DOC_ROOT . $this->getFileurl());
        }
        parent::delete(); // TODO: Change the autogenerated stub
    }

    public function getFileurl(): ?string
    {
        return $this->fields['fileurl'];
    }

}
